targets = [ "//:fizz" ]

[[dependency]]
package = "github.com/buckaroo-pm/facebook-folly"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/facebook-zstd"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/jedisct1-libsodium"
version = "*"

